### ISSUE TITLE
Crash when \u is in path

### ISSUE THREAD

**Issue by woefe** [karlch/vimiv-qt#218]
Steps to reproduce:
1. Create image with filename `r"\uasdf.jpg"`
2. vimiv \\uasdf.jpg
3. delete %%
4. crash:
```
[20:56:25] ERROR    <vimiv>              Uncaught exception! Exiting gracefully and printing stack...
Traceback (most recent call last):
  File "/usr/lib/python3.8/sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\u'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/vimiv/gui/commandline.py", line 91, in <lambda>
    QTimer.singleShot(0, lambda: runners.run(command, mode=self.mode))
  File "/usr/lib/python3.8/site-packages/vimiv/commands/runners.py", line 49, in inner
    return func(text, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/vimiv/commands/runners.py", line 75, in run
    textparts = utils.recursive_split(text, SEPARATOR, update_part)
  File "/usr/lib/python3.8/site-packages/vimiv/utils/__init__.py", line 313, in recursive_split
    splits = updater(text).split(separator)
  File "/usr/lib/python3.8/site-packages/vimiv/commands/runners.py", line 73, in update_part
    return wildcards.expand_internal(alias(text.strip(), mode), mode)
  File "/usr/lib/python3.8/site-packages/vimiv/commands/wildcards.py", line 61, in expand_internal
    text = expand(text, wildcard.wildcard, wildcard, mode)
  File "/usr/lib/python3.8/site-packages/vimiv/commands/wildcards.py", line 88, in expand
    text = re.sub(
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.8/re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.8/re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.8/sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \u at position 13
```
---
vimiv --version
```
vimiv v0.7.0

Python: 3.8.3
Qt: 5.14.2
PyQt: 5.14.2

Svg Support: True
Piexif: None

Paths:
cache: /home/woefe/.cache/vimiv
config: /home/woefe/.config/vimiv
data: /home/woefe/.local/share/vimiv
```

**Comment by karlch** [comment]
Thanks for the detailed report, I can reproduce this bug. Various crashes and errors also happen for other characters than `u` after the backslash. It also seems like it is not limited to the one crash here but backslashes lead to issues at least:
* When referred to in a wildcard due to the reported crash in `commands.wildcards.expand`
* When passed in the command line as they may be removed by the call to `shlex.split` in `commands.runners._parse` or `commands.external.run`

This will require some more careful thinking as we already rely on backslashes for escaping whitespace in the commandline. An option could be to:
* Correctly escape backslashes in the wildcard handling
* Correctly escape backslashes when using the completion
* Rely on the user to escape backslashes in case of manual path entering, e.g.:
`:!mv \a.jpg` would have to be `:!mv \\a.jpg`, much like it is in the shell.
