### ISSUE TITLE
Don't raise if keybind section is not specified

### ISSUE THREAD

**Issue by petobens** [karlch/vimiv-qt#29]
Currently if a keybind section such as `[GLOBAL]` is not specified in `keys.conf` file then we get the following error:
```
Traceback (most recent call last):
  File "/home/pedro/.local/bin/vimiv", line 11, in <module>
    load_entry_point('vimiv==0.1.0', 'gui_scripts', 'vimiv')()
  File "/home/pedro/.local/pipx/venvs/vimiv/lib/python3.7/site-packages/vimiv/vimiv.py", line 249, in main
    startup(sys.argv[1:])
  File "/home/pedro/.local/pipx/venvs/vimiv/lib/python3.7/site-packages/vimiv/vimiv.py", line 59, in startup
    keyfile.parse(args)
  File "/home/pedro/.local/pipx/venvs/vimiv/lib/python3.7/site-packages/vimiv/config/keyfile.py", line 31, in parse
    _read(keyfile)
  File "/home/pedro/.local/pipx/venvs/vimiv/lib/python3.7/site-packages/vimiv/config/keyfile.py", line 66, in _read
    section = parser[mode.name.upper()]
  File "/usr/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'GLOBAL'
```
vimiv should have a set of default that can be overriden by config files and avoid giving errors if they are not specified (a similar behaviour happens in the `vimiv.conf` file where if a setting is not specified then a warning is raised) Thanks!

**Comment by karlch** [comment]
Thanks for pointing this out! The exception is now caught since 983da8a23a8e67eb830798b55c7cbb6aff63ded3, but the behaviour is still to raise a warning.

What behaviour do you think is desirable instead of a warning?

The reason why a warning is raised in the first place, especially for the settings, is that it allows quickly noticing that there are new settings without reading a changelog (which will come as soon as 0.1 is released).

**Comment by petobens** [comment]
Thanks for the quick change. Mmm maybe then add a cli flag with a `--quiet` option?

**Comment by karlch** [comment]
Well, it is already possible to change the log level to error using `--log-level error`, which will accordingly silent the warning messages.

But you have a point, maybe this is too verbose for the default and these types of notifications should be part of log level info, not warning. I have opened #30 for this inconsistency.

**Comment by petobens** [comment]
Great. Feel free to close when you deem fit.
