### ISSUE TITLE
Crash When Deleting Image Without Permission

### ISSUE THREAD

**Issue by jcjgraf** [karlch/vimiv-qt#330]
When one tries to remove an image for which one has no permissions, vimiv crashes. Probably we should handle such cases more gracefully and notify the user that one has not sufficient permissions for a certain action.

<details><summary>Crashlog</summary>
```
[20:14:02] DEBUG    <api.status>         Clearing status messages: KeyPressEvent
[20:14:02] DEBUG    <gui.eventhandler>   EventHandlerMixin: handling x for mode library
[20:14:02] DEBUG    <gui.eventhandler>   EventHandlerMixin: found command for event
[20:14:02] DEBUG    <commands.runners>   Running 'delete %'
[20:14:02] DEBUG    <commands.runners>   Split text into parts '['delete /mnt/thumbdrive/Karte.jpeg']'
[20:14:02] DEBUG    <commands.runners>   Handling part 0 'delete /mnt/thumbdrive/Karte.jpeg'
[20:14:02] ERROR    <vimiv>              Uncaught exception! Exiting gracefully and printing stack...
Traceback (most recent call last):
  File "/usr/lib/python3.9/shutil.py", line 806, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/mnt/thumbdrive/Karte.jpeg' -> '/home/jeanclaude/.local/share/Trash/files/Karte.jpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeanclaude/Documents/Programming/vimiv-qt/vimiv/gui/eventhandler.py", line 142, in keyPressEvent
    elif not self._process_event(keysequence, mode=mode):
  File "/home/jeanclaude/Documents/Programming/vimiv-qt/vimiv/gui/eventhandler.py", line 187, in _process_event
    runners.run(command, count=count, mode=mode)
  File "/home/jeanclaude/Documents/Programming/vimiv-qt/vimiv/commands/runners.py", line 49, in inner
    return func(text, *args, **kwargs)
  File "/home/jeanclaude/Documents/Programming/vimiv-qt/vimiv/commands/runners.py", line 80, in run
    _run_single(cmdpart, mode, count)
  File "/home/jeanclaude/Documents/Programming/vimiv-qt/vimiv/commands/runners.py", line 49, in inner
    return func(text, *args, **kwargs)
  File "/home/jeanclaude/Documents/Programming/vimiv-qt/vimiv/commands/runners.py", line 99, in _run_single
    command(count + text, mode)
  File "/home/jeanclaude/Documents/Programming/vimiv-qt/vimiv/commands/runners.py", line 119, in command
    _run_command(count, cmdname, args, mode)
  File "/home/jeanclaude/Documents/Programming/vimiv-qt/vimiv/commands/runners.py", line 154, in _run_command
    cmd(args, count=count)
  File "/home/jeanclaude/Documents/Programming/vimiv-qt/vimiv/api/commands.py", line 318, in __call__
    objreg._call_with_instance(self.func, **kwargs)
  File "/home/jeanclaude/Documents/Programming/vimiv-qt/vimiv/api/objreg.py", line 73, in _call_with_instance
    return func(*args, **kwargs)
  File "/home/jeanclaude/Documents/Programming/vimiv-qt/vimiv/commands/delete_command.py", line 35, in delete
    trash_filename = trash_manager.delete(filename)
  File "/home/jeanclaude/Documents/Programming/vimiv-qt/vimiv/utils/trash_manager.py", line 52, in delete
    shutil.move(filename, trash_filename)
  File "/usr/lib/python3.9/shutil.py", line 821, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/mnt/thumbdrive/Karte.jpeg'
```</details>

**Comment by karlch** [comment]
Thanks for the report! Sounds good, I will look into it soon :tm:
