### ISSUE TITLE
[BUG] piexif._exceptions.InvalidImageDataError: Given file is neither JPEG nor TIFF. 

### ISSUE THREAD

**Issue by BachoSeven** [karlch/vimiv-qt#370]
ArchLinux, `vimiv-qt-git` installed from AUR, version `r2159.b2f9acbe-1`

Full log:
```
[18:34:32] ERROR    <vimiv>              Uncaught exception! Exiting gracefully and printing stack... 
Traceback (most recent call last): 
  File "/usr/lib/python3.9/site-packages/vimiv/gui/eventhandler.py", line 142, in keyPressEvent 
    elif not self._process_event(keysequence, mode=mode): 
  File "/usr/lib/python3.9/site-packages/vimiv/gui/eventhandler.py", line 187, in _process_event 
    runners.run(command, count=count, mode=mode) 
  File "/usr/lib/python3.9/site-packages/vimiv/commands/runners.py", line 49, in inner 
    return func(text, *args, **kwargs) 
  File "/usr/lib/python3.9/site-packages/vimiv/commands/runners.py", line 80, in run 
    _run_single(cmdpart, mode, count) 
  File "/usr/lib/python3.9/site-packages/vimiv/commands/runners.py", line 49, in inner 
    return func(text, *args, **kwargs) 
  File "/usr/lib/python3.9/site-packages/vimiv/commands/runners.py", line 99, in _run_single 
    command(count + text, mode) 
  File "/usr/lib/python3.9/site-packages/vimiv/commands/runners.py", line 119, in command 
    _run_command(count, cmdname, args, mode) 
  File "/usr/lib/python3.9/site-packages/vimiv/commands/runners.py", line 154, in _run_command 
    cmd(args, count=count) 
  File "/usr/lib/python3.9/site-packages/vimiv/api/commands.py", line 325, in __call__ 
    objreg._call_with_instance(self.func, **kwargs) 
  File "/usr/lib/python3.9/site-packages/vimiv/api/objreg.py", line 72, in _call_with_instance 
    return func(cls.instance, *args, **kwargs) 
  File "/usr/lib/python3.9/site-packages/vimiv/gui/metadatawidget.py", line 109, in metadata 
    self._update_text() 
  File "/usr/lib/python3.9/site-packages/vimiv/gui/metadatawidget.py", line 163, in _update_text 
    formatted_exif = self.handler.get_formatted_exif(keys) 
  File "/usr/lib/python3.9/site-packages/vimiv/gui/metadatawidget.py", line 72, in handler 
    self._handler = exif.ExifHandler(self._path) 
  File "/usr/lib/python3.9/site-packages/vimiv/imutils/exif.py", line 82, in __init__ 
    self._metadata = piexif.load(filename) 
  File "/usr/lib/python3.9/site-packages/piexif/_load.py", line 28, in load 
    exifReader = _ExifReader(input_data) 
  File "/usr/lib/python3.9/site-packages/piexif/_load.py", line 104, in __init__ 
    raise InvalidImageDataError("Given file is neither JPEG nor TIFF.") 
piexif._exceptions.InvalidImageDataError: Given file is neither JPEG nor TIFF. 
```

(I have the optional dependency `python-piexif` installed)

**Comment by jcjgraf** [comment]
Thanks for the report, this looks interesting. What is the filetype of the image you were trying to open?

**Comment by BachoSeven** [comment]
I should have noted, this only happens if I press `i` to activate the metadata-showing widget which uses `piexif`.

The file is a gif, attached:

![1492284782822](https://user-images.githubusercontent.com/55460785/115594112-a8e13f80-a2d5-11eb-8595-c5ec964d8b2a.gif)

**Comment by jcjgraf** [comment]
Thanks you very much for spotting this error. I introduces this bug when adding`pyexiv2` support in #301 :blush:

I have pushed a fix to #371 which @karlch hopefully will merge soon.

**Comment by BachoSeven** [comment]
Thanks! Would you recommend using `pyexiv2` over `piexif`, in terms of filetypes support or else?

**Comment by jcjgraf** [comment]
There are three noticeable differences between the two libraries:
- piexif only supports JPEG and TIFF (and TIFF based like CR2), whereas pyexiv2 supports most common formats
- When using pyexiv2 the output of the widget is format whereas for piexif it is *raw*
- Pyexif is more involve to install (requires exiv2 and some other dependancies)

If you have not done so, I would recommend you to also have a look at the [pyexiv2 vs piexif](https://karlch.github.io/vimiv-qt/documentation/exif.html#advantages-of-the-different-exif-libraries) from the docs. I have extended this section in #371 to indicate that piexif is rather limited in terms of supported types.

**Comment by BachoSeven** [comment]
Right, I thought I read that one of them was better in the docs... I also thought for some reason pyexiv2 wasn't as readily available on my system, but it's in the AUR so I just built that and it works great. Thanks again!
